# Generated by Django 5.2 on 2025-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Credit Card'), ('virement', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='paiement',
            table='paiement_paiement',
        ),
    ]
