# Generated by Django 5.2 on 2025-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
