# Generated by Django 5.2 on 2025-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Property Owner')], max_length=20),
        ),
    ]
